/**
 * AUTO-GENERATED by scripts/generate-dates.mjs — DO NOT EDIT.
 *
 * Single source of truth for date/year/month references across this site.
 * Regenerated as a prebuild step (see root package.json "prebuild" script).
 *
 * Per PPL_SOP.md § 16C + memory:date-freshness.
 *
 * RULE: never hardcode a current-year/month/date elsewhere — import DATES
 * from this file. Build gate scripts/verify-date-freshness.mjs FAILS on
 * any hardcoded current-year occurrence outside the allowed historical set.
 */
import type { SiteDates } from '@ppl/shared/lib/dates';

export const DATES: SiteDates = {
  "builtAt": "2026-06-04",
  "currentYear": 2026,
  "currentYearString": "2026",
  "currentMonth": 6,
  "currentMonthName": "June",
  "currentMonthYear": "June 2026",
  "currentQuarter": "Q2 2026",
  "nextRefreshAfter": "2026-09-02",
  "perRoute": {
    "/about/": "2026-05-31",
    "/affiliate-disclosure/": "2026-05-31",
    "/blog/do-i-need-a-panel-upgrade-for-ev-charger/": "2026-05-31",
    "/blog/ev-charger-install-cost-bend/": "2026-05-31",
    "/blog/hardwired-vs-nema-14-50-ev-charger/": "2026-05-31",
    "/blog/level-1-vs-level-2-ev-charging/": "2026-05-31",
    "/blog/oregon-ev-charger-rebates-guide/": "2026-05-31",
    "/blog/": "2026-05-31",
    "/blog/what-amperage-ev-charger-do-i-need/": "2026-05-31",
    "/contact/": "2026-05-31",
    "/faq/": "2026-06-01",
    "/glossary/": "2026-05-31",
    "/locations/[slug]/": "2026-05-31",
    "/locations/": "2026-05-31",
    "/": "2026-06-01",
    "/privacy/": "2026-05-31",
    "/services/ev-panel-upgrade/": "2026-05-31",
    "/services/level-2-charger-install/": "2026-05-31",
    "/services/multi-unit-ev-charging/": "2026-05-31",
    "/services/nema-14-50-outlet/": "2026-05-31",
    "/services/": "2026-05-31",
    "/terms/": "2026-05-31"
  }
};
