// AUTO-GENERATED by scripts/gen-image-credits.mjs — do not edit by hand.
// Complete per-image licensing/attribution for ImageObject schema (Google Image-License fields).
import type { ImageCredit } from '@ppl/shared/lib/schema-gen';

export const IMAGE_CREDITS: Record<string, ImageCredit> = {
  "about-ev-crew": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/PkHf7BUWbtk",
    "creator": "Toolmash Expo",
    "creditText": "Photo by Toolmash Expo on Unsplash",
    "copyrightNotice": "© Toolmash Expo"
  },
  "blog/amperage": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/28265032",
    "creator": "ranjeet .",
    "creditText": "Photo by ranjeet . on Pexels",
    "copyrightNotice": "© ranjeet ."
  },
  "blog/body/amperage/amperage-dial": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/32725819",
    "creator": "Luke Miller",
    "creditText": "Photo by Luke Miller on Pexels",
    "copyrightNotice": "© Luke Miller"
  },
  "blog/body/amperage/breaker": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/28265032",
    "creator": "ranjeet .",
    "creditText": "Photo by ranjeet . on Pexels",
    "copyrightNotice": "© ranjeet ."
  },
  "blog/body/amperage/car-port": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/17000830",
    "creator": "Vitali Adutskevich",
    "creditText": "Photo by Vitali Adutskevich on Pexels",
    "copyrightNotice": "© Vitali Adutskevich"
  },
  "blog/body/ev-cost/conduit": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/14705219",
    "creator": "Benjamin Farren",
    "creditText": "Photo by Benjamin Farren on Pexels",
    "copyrightNotice": "© Benjamin Farren"
  },
  "blog/body/ev-cost/equipment": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/5391509",
    "creator": "Ed Harvey",
    "creditText": "Photo by Ed Harvey on Pexels",
    "copyrightNotice": "© Ed Harvey"
  },
  "blog/body/ev-cost/permit-panel": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/28265032",
    "creator": "ranjeet .",
    "creditText": "Photo by ranjeet . on Pexels",
    "copyrightNotice": "© ranjeet ."
  },
  "blog/body/hardwired-vs-outlet/hardwired": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/5391509",
    "creator": "Ed Harvey",
    "creditText": "Photo by Ed Harvey on Pexels",
    "copyrightNotice": "© Ed Harvey"
  },
  "blog/body/hardwired-vs-outlet/outlet": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/36272732",
    "creator": "Jan van der Wolf",
    "creditText": "Photo by Jan van der Wolf on Pexels",
    "copyrightNotice": "© Jan van der Wolf"
  },
  "blog/body/hardwired-vs-outlet/wire-run": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/35812856",
    "creator": "Michael",
    "creditText": "Photo by Michael on Pexels",
    "copyrightNotice": "© Michael"
  },
  "blog/body/level-1-vs-2/daily-drive": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/33758075",
    "creator": "Antonio Mistretta",
    "creditText": "Photo by Antonio Mistretta on Pexels",
    "copyrightNotice": "© Antonio Mistretta"
  },
  "blog/body/level-1-vs-2/level-1": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/3846205",
    "creator": "Rathaphon Nanthapreecha",
    "creditText": "Photo by Rathaphon Nanthapreecha on Pexels",
    "copyrightNotice": "© Rathaphon Nanthapreecha"
  },
  "blog/body/level-1-vs-2/level-2": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/5391509",
    "creator": "Ed Harvey",
    "creditText": "Photo by Ed Harvey on Pexels",
    "copyrightNotice": "© Ed Harvey"
  },
  "blog/body/panel-upgrade/load-calc": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/36085816",
    "creator": "Elite Power Group",
    "creditText": "Photo by Elite Power Group on Pexels",
    "copyrightNotice": "© Elite Power Group"
  },
  "blog/body/panel-upgrade/panel-open": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/28265032",
    "creator": "ranjeet .",
    "creditText": "Photo by ranjeet . on Pexels",
    "copyrightNotice": "© ranjeet ."
  },
  "blog/body/panel-upgrade/subpanel": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/30144993",
    "creator": "Anh-Bao Tran-Le",
    "creditText": "Photo by Anh-Bao Tran-Le on Pexels",
    "copyrightNotice": "© Anh-Bao Tran-Le"
  },
  "blog/body/rebates/consult": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/8439696",
    "creator": "Kampus Production",
    "creditText": "Photo by Kampus Production on Pexels",
    "copyrightNotice": "© Kampus Production"
  },
  "blog/body/rebates/home-charger": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/28851165",
    "creator": "Jakub Zerdzicki",
    "creditText": "Photo by Jakub Zerdzicki on Pexels",
    "copyrightNotice": "© Jakub Zerdzicki"
  },
  "blog/body/rebates/rebate-form": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/7567551",
    "creator": "Tima Miroshnichenko",
    "creditText": "Photo by Tima Miroshnichenko on Pexels",
    "copyrightNotice": "© Tima Miroshnichenko"
  },
  "blog/ev-cost": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/3846205",
    "creator": "Rathaphon Nanthapreecha",
    "creditText": "Photo by Rathaphon Nanthapreecha on Pexels",
    "copyrightNotice": "© Rathaphon Nanthapreecha"
  },
  "blog/hardwired-vs-outlet": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/lQa1ZX0R3Os",
    "creator": "Fabian Kleiser",
    "creditText": "Photo by Fabian Kleiser on Unsplash",
    "copyrightNotice": "© Fabian Kleiser"
  },
  "blog/level-1-vs-2": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/wRosknwzpuM",
    "creator": "go-e",
    "creditText": "Photo by go-e on Unsplash",
    "copyrightNotice": "© go-e"
  },
  "blog/panel-upgrade": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/maXnRLszYY0",
    "creator": "Troy Bridges",
    "creditText": "Photo by Troy Bridges on Unsplash",
    "copyrightNotice": "© Troy Bridges"
  },
  "blog/rebates": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/zR7nFjjIAWE",
    "creator": "Jakub Żerdzicki",
    "creditText": "Photo by Jakub Żerdzicki on Unsplash",
    "copyrightNotice": "© Jakub Żerdzicki"
  },
  "hero-ev-charger-bend": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/FQEVUt35IaM",
    "creator": "Priscilla Du Preez 🇨🇦",
    "creditText": "Photo by Priscilla Du Preez 🇨🇦 on Unsplash",
    "copyrightNotice": "© Priscilla Du Preez 🇨🇦"
  },
  "service-level-2": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/17000830",
    "creator": "Vitali Adutskevich",
    "creditText": "Photo by Vitali Adutskevich on Pexels",
    "copyrightNotice": "© Vitali Adutskevich"
  },
  "service-multi-unit": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/gzXa27eRB6A",
    "creator": "Bernd 📷 Dittrich",
    "creditText": "Photo by Bernd 📷 Dittrich on Unsplash",
    "copyrightNotice": "© Bernd 📷 Dittrich"
  },
  "service-nema-outlet": {
    "license": "https://www.pexels.com/license/",
    "acquireLicensePage": "https://www.pexels.com/photo/36272732",
    "creator": "Jan van der Wolf",
    "creditText": "Photo by Jan van der Wolf on Pexels",
    "copyrightNotice": "© Jan van der Wolf"
  },
  "service-panel-upgrade": {
    "license": "https://unsplash.com/license",
    "acquireLicensePage": "https://unsplash.com/photos/maXnRLszYY0",
    "creator": "Troy Bridges",
    "creditText": "Photo by Troy Bridges on Unsplash",
    "copyrightNotice": "© Troy Bridges"
  }
};
